### ISSUE TITLE
Add fading effect on background canvas color change.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/movie-quote-generator#1]
The background canvas changes color instantaneously when a new quote loads. Implementation of a fade in and fade out effect or a smooth transition of the background color would be nice...

**Comment by DimensionalDragon** [comment]
Hi! May I help with this issue? I think I could handle this.

**Comment by kamiri-charles** [comment]
@DimensionalDragon, that would be awesome. Lemme assign you.
