### ISSUE TITLE
Add a way for contributors to the project to be acknowledged on the site.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/movie-quote-generator#12]

**Comment by ryanpjhickey** [comment]
Hi Charles, I've gone ahead and created a simple implementation with clickable github icons that link to the corresponding github profile pages. I put in a PR [here](https://github.com/kamiri-charles/movie-quote-generator/pull/13) but please let me know if you would like something different and I'm happy to implement it!

**Comment by ryanpjhickey** [comment]
I just went ahead and coded this up. You can review the PR [here](https://github.com/kamiri-charles/movie-quote-generator/pull/14). Let me know if this works for you!
