### ISSUE TITLE
Background color change on load_quote.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/movie-quote-generator#16]
The background color of the page should transition to a new color when a new quote is loaded...

**Comment by sankalp-12** [comment]
Could you provide me some guidance on how to build the app on my local machine. Thank you!

**Comment by kamiri-charles** [comment]
Hey, @sankalp-12 . After forking or downloading the 'zip' file, the basic command is `npm start` which starts the app in dev mode on localhost:3000. If you face any dependency error(s) you can run `npm install` which installs all the dependecies required. You can also use these other commands. https://create-react-app.dev/docs/available-scripts
