### ISSUE TITLE
Responsive design on different devices.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/movie-quote-generator#2]
The design on mobile phones is a bit uneasy. Some updates would be nice.

**Comment by aryan1306** [comment]
Hi @kamiri-charles can you assign this to me?

**Comment by kamiri-charles** [comment]
Assigned @aryan1306

**Comment by aryan1306** [comment]
Hey, @kamiri-charles, i have raised a [PR](https://github.com/kamiri-charles/movie-quote-generator/pull/10) for this. Please do your review.

**Comment by kamiri-charles** [comment]
Hey, @aryan1306 , if you're free. There have been some frequent updates to the page and the design on mobile isn't looking good. However, it's ok if ur unavailable...

**Comment by Josh-D18** [comment]
Hey @kamiri-charles  is it ok if I work on the responsive design?

**Comment by kamiri-charles** [comment]
@Josh-D18 , that would be awesome

**Comment by Josh-D18** [comment]
Hey @kamiri-charles, I made a PR for this issue at https://github.com/kamiri-charles/movie-quote-generator/pull/18.
