### ISSUE TITLE
More lenguajes

### ISSUE THREAD

**Issue by jcbotero** [kamiri-charles/movie-quote-generator#30]
Hello,

 how about including some buttons that translate into different languages, to give the application a greater impact?.

**Comment by johnspeed114** [comment]
@jcbotero What would be a great idea. 
What translation apis do you want use? I usually use Google Translate. What you do you think?

cc:
@kamiri-charles

**Comment by kamiri-charles** [comment]
I don't have a lot of experience with language APIs...what can you recommend? @johnspeed114

**Comment by johnspeed114** [comment]
Here are a few that are high quality that recommended with details on each services and free tier, but based our # of visits/requests each of the services varies for their free tier. What is the # of requests currently and the expectation for the future? @kamiri-charles 

1. Microsoft Text Translation API: This API is a great choice as it supports a wide variety of languages, and it offers 2 million characters per month for free. This is quite a generous offer and should be more than sufficient for a movie quote generator app, unless you're dealing with a very high volume of traffic​[1](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/)​.

2. Linguatools Translate API: This API offers 1,000 free requests per month. If each movie quote counts as a single request, this could also be a reasonable option. However, if you exceed the limit, you'll be charged $0.001 per additional request. The cost-effectiveness of this API would depend on the volume of traffic you expect on your site​[2](https://rapidapi.com/petapro/api/linguatools-translate/pricing)​.

3. Google Translate: This is one of the most popular translation services. It supports a very wide range of languages and often produces quite accurate translations, particularly for common language pairs like English-Spanish or English-French. However, it can sometimes struggle with more complex sentences or less common languages. Morever, it's important to consider the cost associated with its usage. Google Translate API offers 500,000 characters per month for free, but after that, it becomes a paid service​[3](https://translatepress.com/docs/automatic-translation/generate-google-api-key/)​.

4. DeepL: DeepL has gained a reputation for high-quality translations. Some users have reported that it provides more accurate and natural-sounding translations than Google, particularly for European languages. However, it supports fewer languages than Google Translate.

**Comment by Ironman0505** [comment]
Hello @jcbotero ,I want to contribute on this issue. Do you want to add an extra button that can translate to other languages? I am excited to contribute to your project.

**Comment by Ironman0505** [comment]
Hello ,I want to contribute to your project. Do you want to add an extra button that can translate to other languages? I am excited to work on the issue.

**Comment by Ironman0505** [comment]
Hey, I have tried to convert the content  entered, from english language to arabic. Here is the code

```
const translate = async () => {
    let res = await fetch('https://libretranslate.de/translate', {
      method: 'POST',
      body: JSON.stringify({
        q: data,
        source: 'auto',
        target: 'ar',
        format: 'text',
        api_key: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      }),
      headers: { 'Content-Type': 'application/json' },
    });
    let ne = await res.json();
    console.log(ne);
    let dt = ne.translatedText;
    setT(dt);
  };
```
  
  I have used the Libretranslate API to translate....But this API takes maximum upto 25 characters...and it doesnt convert all the words(There are only some specific words that are predefined to that api which gets converted). Can You further guide me in how to improve it.
  
**The working of this API translation is shown Below in a sample code....**

![image](https://github.com/kamiri-charles/movie-quote-generator/assets/91952779/c2c725f0-0c3b-465d-90e4-b732dc12e6a9)

  
**Here is the extra button i have added to ensure translation..**

![image](https://github.com/kamiri-charles/movie-quote-generator/assets/91952779/2bfced90-f0da-43c6-9a42-fbe6c90e74d6)

Thanks.

**Comment by johnspeed114** [comment]
@Ironman0505 The issue with Libretranslate API is a self-hosted translation API, that means you need to it to be installed and runing on a server, physical or cloud. This is a public instance of LibreTranslate hosted by a third party, and it's possible that they've configured it in a way that's causing the issues you're experiencing. For a small project like this, this is why I recommended the using any of the services that mentioned above.  

cc.
@kamiri-charles

**Comment by kamiri-charles** [comment]
I was actually reviewing this issue and I don't think we need a translator.
    1. Most modern browsers have automatic translators inbuilt i.e. Google Translate
    2. The app is relatively small and there's no need to make it really complex
   
I will however wait for input from @jcbotero, @johnspeed114 , @Ironman0505 and @sgtwilko on this issue

**Comment by johnspeed114** [comment]
@kamiri-charles thanks for the response. I will give you my thoughts on it, but since I don't know full vision of this project I will let you decide.

> 1. Most modern browsers have automatic translators inbuilt i.e. Google Translate

Yes, but for the user you have to go out your way manually translate it, especially if the default language on your brower is not language you want to translate into. Making the user experience not that usable.

> 2. The app is relatively small and there's no need to make it really complex

The code itself isn't that complex. Like @Ironman0505 code example above, you just need fetch with the content in body and an api key. However, there is an extra layer of complexity with API key management we would need to find a hosting platform(Heroku or Docker) and creating new env files for development and production. You would also need to keep up to date on the translation service, wheater if the updated their apis, free tier restrictions, and security updates.
