### ISSUE TITLE
Any performance and design improvements.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/movie-quote-generator#4]

**Comment by Dev-Dannie** [comment]
Is this issue still open for collab? I will like to help

**Comment by kamiri-charles** [comment]
Hey @Dev-Dannie , it's still open for collab, just create a PR...

**Comment by HC-bentill** [comment]
I would want to work on this issue please

**Comment by kamiri-charles** [comment]
@HC-bentill it's still open for contributions

**Comment by salamisodikiolawale** [comment]
Hey @Dev-Dannie , I am interested in your project, I would like to bring to the project a containerization system to facilitate the development and the handling of the project by developers. Are you interested in this ?

**Comment by lakshaysharma14** [comment]
I would like to suggest few improvement that can be added :

- Project Can be Migrated to Use Typescript.
- Pre-Commit Hook with Lint Check and Formatting Can be Added. 
- PR-Template Can be Added.

@kamiri-charles let me know if these points sounds ok to you and you are Interested.

**Comment by kamiri-charles** [comment]
@lakshaysharma14 Sounds awesome...Go for it.

**Comment by DBorhara** [comment]
I would like to suggest a couple of quick improvements I can add :
- Modifying change_color so it works to make bg colors more appealing.
- Implementing useCallBack to store functions so they dont get called each re-render.
- A toast component or message when the user clicks copy instead of alert.

**Comment by kamiri-charles** [comment]
@DBorhara sounds awesome. Go for it.

**Comment by SumitGupta016** [comment]
Hi @kamiri-charles This project needs better Documentation and I can help with that, So should I do it for this?
Let me know so I start working on it !

**Comment by NealePT** [comment]
Hi I'd like to work on the copy function, it doesn't seem to be working properly on Chrome. I want to also change the alert to a toast if it isn't be worked on already!

**Comment by johnspeed114** [comment]
Hi @kamiri-charles I am interested in working on your project! Also, thank you starting this project up. 
Just a small improvement I think you can make. Below is the git that you mention in the documentation to clone the code to the local. 
`git clone https://github.com/your-username/movie-quote-generator.git`

However, it would would give this error, below.

> fatal: repository 'https://github.com/johnspeed114/movie-quote-generator.git/' not found

To this fix this confusion, I think we should change the documentation to 
`git clone https://github.com/kamiri-charles/movie-quote-generator.git`

What do you think?

**Comment by kamiri-charles** [comment]
@johnspeed114 that would be awesome. Though I think it was supposed to be fork the repo on GitHub before cloning it locally....
Go for it.

**Comment by johnspeed114** [comment]
@kamiri-charles how about this, below? I added the fork section for the documentation for clarification, and then modify the cloning and local installation section to help integrate with with the fork section.
### Forking the Repository
Here are the steps to fork the movie-quote-generator repository:

1. **Start the Fork Process:** On the top-right of this page, you'll see a button labeled "Fork". Click on it. This will start the process of creating a fork of the repository.
2. **Select Your Account:** If you're part of any organizations, GitHub will ask where you want to fork the repository. Select your personal GitHub account.
3. **Wait for the Fork to Complete:** GitHub will take a few seconds to complete the fork. Once it's done, you'll be automatically redirected to your new forked repository.

### Cloning the Forked Repository
After forking the repository, you might want to clone it to your local machine to work on the code. Follow these steps:

1. **Copy the Repository URL:** On your forked repository page, click the green "Code" button. This will reveal the URL to your repository. Copy it.
2. **Clone the Repository:** Open a terminal on your local machine. Navigate to the directory where you want to clone the repository and run:

`git clone https://github.com/YOUR_USERNAME/movie-quote-generator.git`

Make sure to replace YOUR_USERNAME with your actual GitHub username.

3. **Navigate to the Cloned Directory:** Once the cloning process is finished, navigate to the project directory by typing:

`cd movie-quote-generator`

### Installing and Running the Project Locally
After cloning the repository, you can install and run the movie-quote-generator locally on your own computer by following these steps:

1. **Install the Dependencies:** While in the project root directory, run the following command to install all the necessary dependencies:

`npm install`

2. **Start the Development Server:** After the installation is complete, you can start the application development server by running:

`npm start`

3. **Access the Application:** If the application does not open automatically in your default web browser, copy and paste this URL to the browser's address bar:

`http://localhost:3000/movie-quote-generator`

This assumes that port 3000 is not being used by another React App. If it is, you can use other ports like 3001, 3002, 3003, etc.

**Comment by kamiri-charles** [comment]
@johnspeed114 looks cool. Just make a pull request

**Comment by johnspeed114** [comment]
@kamiri-charles created a PR, below
https://github.com/kamiri-charles/movie-quote-generator/pull/41

**Comment by johnspeed114** [comment]
@kamiri-charles I noticed that some of the components are a mix between js and jsx files. Was there any reasoning behind this? Because the code within the js files like QuoteGenerator.js or Contributors.js are clearly using jsx. 
Also, there are some not great practicies (redundant prop destructure) and UI bugs fixes I plan to fix. I will start on them tomorrow.

**Comment by 0ME9A** [comment]
Hey, guys please tell me if someone working on UI if not then I'm interested to give an awesome and attractive look to it✨🧑‍💻

**Comment by lemorage** [comment]
Hey @kamiri-charles, what about utilizing system fonts on the end user's computer? We can allow users to view the content in their preferred font, which they have set up on their system. This little enhancement could improve the user experience. What are your thoughts on this?

**Comment by kamiri-charles** [comment]
Sounds awesome but the styling for the quotes isn't that bad. I think we should keep it that way @lemorage
